version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: teste
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  devweb2-app:
    build: .
    ports:
      - "9090:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
